version: "3.8"

services:
  db:
    image: postgres:13
    container_name: my_postgres
    environment:
      POSTGRES_DB: auk_blog
      POSTGRES_USER: lev
      POSTGRES_PASSWORD: default
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
